[project]
name = "metappuccino"
version = "1.0.0"
description = "Metappuccino CLI"
readme = "README.md"
requires-python = ">=3.9"
license = "Apache-2.0"
authors = [{name="Fiona Hak"}]
dependencies = ["numpy", "psutil", "rich", "requests", "pandas", "spacy", "scikit-learn", "nltk", "transformers", "torch", "llama-cpp-python", "openpyxl", "pyarrow", "fastparquet", "matplotlib"]

[project.scripts]
metappuccino = "metappuccino.cli:main"

[build-system]
requires = ["setuptools>=68","wheel","build"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
[tool.setuptools]
include-package-data = true
