import csv
import re

cell_type_dict = {
    "H9_hESC": "embryonic stem cell",
    "tumor associated T-cell": "T cell",
    "epithelial cell of prostate": "epithelial cell",
    "fibroblast of lung": "fibroblast",
    "immortalized embryonic kidney cell": "epithelial cell",
    "immortalized embryonic kidney cell": "epithelial cell",
    "pluripotent stem cell": "pluripotent stem cell",
    "hiPS cell derived kidney organoids": "kidney epithelial cell",
    "hiPS cell derived IPCs, replicate2": "pancreatic endocrine cell",
    "hiPS cell derived IPCs": "pancreatic endocrine cell",
    "hiPS cell derived PPS": "pancreatic progenitor cell",
    "1_control cell": "nan",
    "synovial stem cells": "mesenchymal stem cell",
    "adipose stem cells": "mesenchymal stem cell",
    "mucoepidermoid carcinoma": "epithelial cell",
    "myoepithelial carcinoma": "epithelial cell",
    "leukocyte": "white blood cell",
    "Human Endocardial Cells": "endocardial cell",
    "Human Common Carotid Artery": "endothelial cell",
    "Human Pulmonary Artery Endothelial Cells": "endothelial cell",
    "Human Cardiac Microvascular Endothelial Cells": "endothelial cell",
    "endothelial cell of umbilical artery": "endothelial cell",
    "colon cancer": "epithelial cell",
    "mast cell": "mast cell",
    "lymphoid cell": "lymphocyte",
    "megakaryoblast": "megakaryocyte progenitor cell",
    "trophoblast cell": "trophoblast",
    "hepatic sinusoidal endothelial cell": "endothelial cell",
    "pneumocyte": "lung epithelial cell",
    "astrocytoid": "astrocyte",
    "lung fibroblast": "fibroblast",
    "cord blood cultured HSC": "hematopoietic stem cell",
    "chronic myelogenous leukemia cell": "leukemic cell",
    "cervical adenocarcinoma cell": "epithelial cell",
    "induced presomitic mesoderm cell": "mesodermal cell",
    "KU812": "leukemic cell",
    "cell line": "nan",
    "hiPS cell derived IPCs, no RA, replicate2": "pancreatic endocrine cell",
    "hiPS cell derived IPCs, replicate1": "pancreatic endocrine cell",
    "4_KLHDC7B knockdown cell": "nan",
    "2_control cell": "nan",
    "blood endothelial cells": "endothelial cell",
    "T lymphoblast": "T cell",
    "Brest adenocarcinoma cell": "epithelial cell",
    "Breast adenocarcinoma cell": "epithelial cell",
    "endocardial cell": "endocardial cell",
    "saphenous vein endothelial cell": "endothelial cell",
    "adrenal cortex cell": "epithelial cell",
    "preadipocyte": "adipocyte progenitor",
    "tumor associated macrophage": "macrophage",
    "F36P": "leukemic cell",
    "epithelial cell (KRAS CRM)": "epithelial cell",
    "iPS cell": "induced pluripotent stem cell",
    "t cell": "T cell",
    "smooth muscle cell": "smooth muscle cell",
    "neural progenitor cell": "neural stem cell",
    "Meg01": "megakaryocyte progenitor cell",
    "germ cell": "germ cell",
    "mesenchymal stem cell of the bone marrow": "mesenchymal stem cell",
    "adipose tissue derived mesenchymal stem cell": "mesenchymal stem cell",
    "Retinal epithelial cell": "retinal pigment epithelial cell",
    "megkaryocyte progenitors derived from human iPSC": "megakaryocyte progenitor cell",
    "Human Umbilical Vein Endothelial Cell": "endothelial cell",
    "Human clear cell renal cell carcinoma": "epithelial cell",
    "adenoid cystic carcinoma": "epithelial cell",
    "CD4CD45RO T cell": "T cell",
    "Nephron progenitor cell": "nephron progenitor cell",
    "Human iPSCs": "induced pluripotent stem cell",
    "MDS/AML": "leukemic cell",
    "lymphatic endothelial cells": "endothelial cell",
    "embryonic kidney cells": "epithelial cell",
    "human hepatocellular carcinoma cell": "epithelial cell",
    "B cells": "B cell",
    "great saphenous vein endothelial cell": "endothelial cell",
    "neuroblast": "neuroblast",
    "epithelial-like": "epithelial cell",
    "MCF7": "epithelial cell",
    "neuroblastoma cell": "neuroblastoma cell",
    "T helper 2 cell": "T cell",
    "endothelial cell": "endothelial cell",
    "melanoma": "melanocyte",
    "HeLa Tet-Off Cell": "epithelial cell",
    "mesenchymal stem cells": "mesenchymal stem cell",
    "biphasic": "nan",
    "bile duct cancer cell": "epithelial cell",
    "CRC": "colorectal cancer cell",
    "cancer cell line": "cancer cell",
    "B lymphoblast": "B cell",
    "T cell, CD8+": "T cell",
    "H9_hESC_clone": "embryonic stem cell",
    "Melanoma": "melanocyte",
    "HaCaT": "keratinocyte",
    "type II pneumocyte": "lung epithelial cell",
    "prostate gland cancer cell": "epithelial cell",
    "regulatory T cell": "T cell",
    "mesothelial cell": "epithelial cell",
    "Breast cancer": "epithelial cell",
    "Nomal Human Dermal Fibroblasts": "fibroblast",
    "hepatocellular carcinoma": "epithelial cell",
    "CD4+CADM1+Tcells (blood)": "T cell",
    "human cervical carcinoma cell Line": "epithelial cell",
    "hTERT immortalized human umbilical vein endothelial cell line": "endothelial cell",
    "human pulmonary microvascular endothelial cells": "endothelial cell",
    "CD4 T cell": "T cell",
    "renal cell carcinoma": "epithelial cell",
    "cell culture": "Primary tissue",
    "Human Coronary Artery Endothelial Cells": "endothelial cell",
    "aortic endothelial cell": "endothelial cell",
    "endothelial cell of artery": "endothelial cell",
    "endocervical carcinoma": "epithelial cell",
    "Colon cancer cells": "colorectal cancer cell",
    "human papillomavirus 16 (HPV-16) transformed": "epithelial cell",
    "b cell": "B cell",
    "CD8-positive, alpha-beta T cell": "T cell",
    "Th17": "T cell",
    "cortical astrocyte": "astrocyte",
    "MM1.S": "myeloma cell",
    "T helper 1 cell": "T cell",
    "T cells": "T cell",
    "derived from cervical cancer": "epithelial cell",
    "human primary leukocytes": "white blood cell",
    "Human leukeima": "leukemic cell",
    "human dermal papilla cell": "fibroblast",
    "prostate cancer": "epithelial cell",
    "Th1": "T cell",
    "ovarian serous carcinoma cell": "epithelial cell",
    "mammary epithelial cell": "epithelial cell",
    "retinal pigment epithelial cell": "retinal pigment epithelial cell",
    "ovarian epithelial cell": "epithelial cell",
    "alpha-beta CD8+ T cells": "T cell",
    "Keratinocyte": "keratinocyte",
    "salivary duct carcinoma": "epithelial cell",
    "HUVEC": "endothelial cell",
    "human embryonic kidney cell": "epithelial cell",
    "unclassifiable": "nan",
    "Immortal cell line of cervical cancer": "epithelial cell",
    "macrophage": "macrophage",
    "human T-cell": "T cell",
    "immortalized human fallopian tube secretory epithelial cell": "epithelial cell",
    "CD8CD45RO T cell": "T cell",
    "embryonic stem cells derived human intestinal organoids": "epithelial cell",
    "myeloblast": "myeloid cell",
    "PBMCs": "white blood cell",
    "cardiocyte": "cardiac muscle cell",
    "skeletal muscle myoblast": "skeletal muscle cell",
    "megakaryocytes derived from human iPSC": "megakaryocyte",
    "primary cell": "Primary tissue",
    "B-cell": "B cell",
    "spatial": "nan",
    "T helper 9 cell": "T cell",
    "Mesothelial cell from ascites": "epithelial cell",
    "Hepatocellular carcinoma": "epithelial cell",
    "Human liver cancer cell line": "epithelial cell",
    "Burkitt lymphoma": "lymphoma cell",
    "intestinal epithelial cell": "epithelial cell",
    "human proximal tubular epithelial cell": "epithelial cell",
    "human corneal epithelial cell": "epithelial cell",
    "keratinocyte": "keratinocyte",
    "Treg": "T cell",
    "embryonic stem cell": "embryonic stem cell",
    "MYELOID CELLS": "myeloid cell",
    "CD4 positive T cell": "T cell",
    "lymphocyte": "lymphocyte",
    "megakaryocyte progenitors derived from human iPSC": "megakaryocyte progenitor cell",
    "osteosarcoma": "osteoblast",
    "chondrocyte": "chondrocyte",
    "erythrocyte": "red blood cell",
    "monocyte derived macrophages": "macrophage",
    "endothelial cell of umbilical vein": "endothelial cell",
    "induced pluripotent stem cell": "induced pluripotent stem cell",
    "Primary B cells": "B cell",
    "adenocarcinoma": "epithelial cell",
    "Kidney organoid": "kidney epithelial cell",
    "CELL MIXTURE - tissue sample": "nan",
    "brain microvascular endothelial cell": "endothelial cell",
    "Primary": "Primary tissue",
    "Peripheral blood T cell": "T cell",
    "pulmonary endothelial cell": "endothelial cell",
    "CD8-Positive T-Lymphocytes": "T cell",
    "striatum neuron": "neuron",
    "CD4-positive helper T cell": "T cell",
    "Fibroblast": "fibroblast",
    "colorectal cancer cell": "epithelial cell",
    "monocyte": "monocyte",
    "epithelial cell": "epithelial cell",
    "hepatocyte": "hepatocyte",
    "fibroblast": "fibroblast",
    "natural killer cell": "NK cell",
    "helper T cell": "T cell",
    "cytotoxic T cell": "T cell",
    "B cell": "B cell",
    "T cell": "T cell",
    "mononuclear cell": "white blood cell",
    "astrocyte": "astrocyte",
    "epithelial": "epithelial cell",
    "nan": "nan",
    "Primary tissue": "Primary tissue"
}

def normalize_cell_type(text):
    if "cell_type:" not in text:
        return text

    before, after = text.split("cell_type:", 1)
    after = after.lstrip()

    for raw, canonical in cell_type_dict.items():
        if after.startswith(raw):
            suffix = after[len(raw):]
            return before + "cell_type: " + canonical + suffix

    return text

def main():
    input_file = '/store/EQUIPES/SSFA/MEMBERS/fiona.hak/MetaMap/results/FINE_TUNING/finetune_clean_cl_tt_data.csv'
    output_file = '/store/EQUIPES/SSFA/MEMBERS/fiona.hak/MetaMap/results/FINE_TUNING/finetune_clean_cl_tt_ct_final_data.csv'

    with open(input_file,  newline='', encoding='utf-8') as inf,\
         open(output_file, 'w', newline='', encoding='utf-8') as outf:
        reader = csv.DictReader(inf)
        writer = csv.DictWriter(outf, fieldnames=reader.fieldnames)
        writer.writeheader()

        for row in reader:
            row["output"] = normalize_cell_type(row.get("output", ""))
            writer.writerow(row)

if __name__ == "__main__":
    main()
